name: independent_temperature_and_moku
components: [moku, temp-control]
run_settings_file: includes/run_settings.yaml
temperature_schedule_file: includes/temperature_two_stage.yaml
pulse_schedule_file: includes/independent_temperature_and_moku_pulses.yaml
end_when: all_schedules_complete
