"""Generate either a traditional pulse or custom Moku:Go pulse sequences.

Edit the user settings below, then validate without connecting:

    python pulse_control.py --dry-run --save-preview pulse_previews

Only run without ``--dry-run`` after checking the EOM input and requested
voltages.  Finite custom repetitions are timed by the Moku:Go AWG's hardware
NCycle burst mode; Python only waits for completion and performs cleanup.
"""

import argparse
import csv
from datetime import datetime, timezone
import json
import math
from pathlib import Path
import sys
import time
from zoneinfo import ZoneInfo

import matplotlib.pyplot as plt
import numpy as np


SCRIPT_DIRECTORY = Path(__file__).resolve().parent
SRC_DIRECTORY = SCRIPT_DIRECTORY / "src"
if str(SRC_DIRECTORY) not in sys.path:
    sys.path.insert(0, str(SRC_DIRECTORY))

from eom_stabilisation.moku.pulse_sequences import (  # noqa: E402
    CompiledCustomSequence,
    TraditionalPulse,
    compile_custom_program,
    validate_traditional_pulse,
)


# =========================
# User settings
# =========================

MOKU_IP = "MokuGo-008058"
OUTPUT_CHANNEL = 2

# Choose "traditional" or "custom".  The default retains the original
# repeating duty-cycle pulse behavior.
PULSE_MODE = "traditional"

# Connector voltages requested from Moku:Go.  The EOM voltage may differ due
# to the apparatus impedance arrangement; this script does not infer it.
LOW_LEVEL_V = 0.0
HIGH_LEVEL_V = 5.0

# Traditional repeating Pulse waveform.
TRADITIONAL_FREQUENCY_HZ = 100.0
TRADITIONAL_DUTY_CYCLE_PERCENT = 0.1
TRADITIONAL_EDGE_TIME_S = 100e-9

# None means repeat until Ctrl+C.  Set a positive number to turn the output off
# automatically after that many seconds.
TRADITIONAL_RUN_DURATION_S = None

# A pulse duration includes its rising edge, high-level plateau, and falling
# edge.  edge_time_s may be set separately for every pulse; when omitted, the
# default below is used.  Consecutive gaps are allowed and remain separate in
# the timing report.
DEFAULT_CUSTOM_EDGE_TIME_S = 100e-9
CUSTOM_SEQUENCES = [
    {
        "name": "example_two_pulse_sequence",
        "segments": [
            {"type": "pulse", "duration_s": 10e-6, "edge_time_s": 100e-9},
            {"type": "gap", "duration_s": 5e-6},
            {"type": "pulse", "duration_s": 20e-6, "edge_time_s": 100e-9},
            {"type": "gap", "duration_s": 50e-6},
            {"type": "gap", "duration_s": 250e-6},
        ],
        # Integer: hardware repeats exactly this many cycles and stops.
        # None: repeat continuously until Ctrl+C.
        "repeat_count": 10,
    },
]

# Multiple finite entries in CUSTOM_SEQUENCES run in order.  This is only a
# minimum software-side pause; waveform upload/API latency means the interval
# between different entries is not deterministic.  Timing inside each entry is
# generated by hardware and is deterministic within Moku:Go specifications.
INTER_SEQUENCE_DELAY_S = 0.0
COMPLETION_MARGIN_S = 0.05

REQUIRE_START_CONFIRMATION = True
FORCE_CONNECT = False
OUTPUT_ROOT = SCRIPT_DIRECTORY / "Experiment Results" / "pulse_programs"
UK_TIME = ZoneInfo("Europe/London")
MOKU_GO_OUTPUT_CHANNELS = (1, 2)


def _timestamp_pair():
    """Return matching UTC and Europe/London ISO timestamps."""
    timestamp_utc = datetime.now(timezone.utc)
    return timestamp_utc.isoformat(), timestamp_utc.astimezone(UK_TIME).isoformat()


def parse_arguments():
    parser = argparse.ArgumentParser(
        description="Generate validated traditional or custom Moku:Go pulses."
    )
    parser.add_argument(
        "--mode",
        choices=["traditional", "custom"],
        help="override PULSE_MODE for this run",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="validate and print the plan without importing Moku or connecting",
    )
    parser.add_argument(
        "--save-preview",
        type=Path,
        metavar="FOLDER",
        help="save requested waveform previews without changing hardware",
    )
    parser.add_argument(
        "--yes",
        action="store_true",
        help="start output without requiring the operator to type START",
    )
    return parser.parse_args()


def _validate_common_settings():
    if OUTPUT_CHANNEL not in {1, 2}:
        raise ValueError("OUTPUT_CHANNEL must be 1 or 2 on Moku:Go")
    if not isinstance(FORCE_CONNECT, bool):
        raise ValueError("FORCE_CONNECT must be True or False")
    try:
        delay = float(INTER_SEQUENCE_DELAY_S)
        margin = float(COMPLETION_MARGIN_S)
    except (TypeError, ValueError) as error:
        raise ValueError(
            "INTER_SEQUENCE_DELAY_S and COMPLETION_MARGIN_S must be numeric"
        ) from error
    if not math.isfinite(delay) or delay < 0:
        raise ValueError("INTER_SEQUENCE_DELAY_S must be finite and non-negative")
    if not math.isfinite(margin) or margin < 0:
        raise ValueError("COMPLETION_MARGIN_S must be finite and non-negative")


def build_plan(mode):
    """Validate settings and return a traditional or compiled custom plan."""
    _validate_common_settings()
    if mode == "traditional":
        config = validate_traditional_pulse(
            TraditionalPulse(
                low_level_v=LOW_LEVEL_V,
                high_level_v=HIGH_LEVEL_V,
                frequency_hz=TRADITIONAL_FREQUENCY_HZ,
                duty_cycle_percent=TRADITIONAL_DUTY_CYCLE_PERCENT,
                edge_time_s=TRADITIONAL_EDGE_TIME_S,
            )
        )
        if TRADITIONAL_RUN_DURATION_S is not None:
            try:
                duration = float(TRADITIONAL_RUN_DURATION_S)
            except (TypeError, ValueError) as error:
                raise ValueError(
                    "TRADITIONAL_RUN_DURATION_S must be positive or None"
                ) from error
            if not math.isfinite(duration) or duration <= 0:
                raise ValueError(
                    "TRADITIONAL_RUN_DURATION_S must be positive or None"
                )
        return config

    if mode == "custom":
        return compile_custom_program(
            CUSTOM_SEQUENCES,
            low_level_v=LOW_LEVEL_V,
            high_level_v=HIGH_LEVEL_V,
            default_edge_time_s=DEFAULT_CUSTOM_EDGE_TIME_S,
        )
    raise ValueError("PULSE_MODE must be 'traditional' or 'custom'")


def display_plan(mode, plan):
    print("\nMoku:Go pulse plan")
    print("==================")
    print(f"Mode: {mode}")
    print(f"Physical output: Output {OUTPUT_CHANNEL}")
    print(f"Requested connector levels: {LOW_LEVEL_V:g} V to {HIGH_LEVEL_V:g} V")
    print(f"Force-connect to an occupied Moku: {FORCE_CONNECT}")

    if mode == "traditional":
        print(f"Frequency: {plan.frequency_hz:g} Hz")
        print(f"Duty cycle: {plan.duty_cycle_percent:g} %")
        print(f"Pulse width: {plan.pulse_width_s * 1e6:.9g} us")
        print(f"Edge time: {plan.edge_time_s * 1e9:.9g} ns")
        run_text = (
            "until Ctrl+C"
            if TRADITIONAL_RUN_DURATION_S is None
            else f"for {float(TRADITIONAL_RUN_DURATION_S):g} s"
        )
        print(f"Output duration: {run_text}")
        return

    for index, compiled in enumerate(plan, start=1):
        summary = compiled.summary_dict()
        repeat_text = (
            "continuous"
            if compiled.sequence.repeat_count is None
            else f"x{compiled.sequence.repeat_count}"
        )
        print(f"\n{index}. {compiled.sequence.name} ({repeat_text})")
        print(f"   Sequence period: {compiled.sequence.period_s * 1e6:.9g} us")
        print(f"   AWG cycle frequency: {compiled.frequency_hz:.9g} Hz")
        print(
            f"   LUT: {len(compiled.lut_data):,} points; "
            f"{compiled.sample_rate_name} conservative memory mode"
        )
        print(f"   LUT interval: {compiled.point_interval_s * 1e9:.9g} ns")
        print(
            "   Maximum duration/edge quantization error: "
            f"{compiled.maximum_timing_error_s * 1e9:.9g} ns"
        )
        if summary["burst_duration_s"] is not None:
            print(f"   Total hardware burst: {summary['burst_duration_s']:.9g} s")
        for segment_index, segment in enumerate(
            compiled.quantized_segments, start=1
        ):
            details = (
                f"requested {segment.requested_duration_s * 1e6:.9g} us, "
                f"actual {segment.actual_duration_s * 1e6:.9g} us"
            )
            if segment.kind == "pulse":
                details += (
                    f", programmed LUT edge requested "
                    f"{segment.requested_edge_time_s * 1e9:.9g} ns, "
                    f"actual {segment.actual_edge_time_s * 1e9:.9g} ns"
                )
            print(f"   {segment_index}: {segment.kind}: {details}")


def _atomic_save_figure(fig, path):
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary_path = path.with_suffix(path.suffix + ".tmp")
    fig.savefig(
        temporary_path,
        format="png",
        dpi=200,
        bbox_inches="tight",
    )
    temporary_path.replace(path)


def save_traditional_preview(config, output_path):
    time_axis = np.linspace(0.0, config.period_s, 2_000, endpoint=False)
    voltage = np.full_like(time_axis, config.low_level_v)
    pulse_mask = time_axis < config.pulse_width_s
    pulse_time = time_axis[pulse_mask]
    if len(pulse_time):
        rising = pulse_time < config.edge_time_s
        falling = pulse_time > config.pulse_width_s - config.edge_time_s
        voltage[pulse_mask] = config.high_level_v
        voltage[np.flatnonzero(pulse_mask)[rising]] = (
            config.low_level_v
            + (config.high_level_v - config.low_level_v)
            * pulse_time[rising]
            / config.edge_time_s
        )
        voltage[np.flatnonzero(pulse_mask)[falling]] = (
            config.low_level_v
            + (config.high_level_v - config.low_level_v)
            * (config.pulse_width_s - pulse_time[falling])
            / config.edge_time_s
        )

    fig, ax = plt.subplots(figsize=(11, 4.5))
    ax.plot(time_axis * 1e6, voltage)
    ax.set_title("Traditional Moku:Go pulse preview")
    ax.set_xlabel("Time within period (µs)")
    ax.set_ylabel("Requested connector voltage (V)")
    ax.grid(True, alpha=0.3)
    fig.tight_layout()
    _atomic_save_figure(fig, output_path)
    plt.close(fig)


def save_custom_preview(compiled, output_path):
    time_axis = np.arange(len(compiled.lut_data)) * compiled.point_interval_s
    voltage = LOW_LEVEL_V + (compiled.lut_data + 1.0) * (
        HIGH_LEVEL_V - LOW_LEVEL_V
    ) / 2.0
    fig, ax = plt.subplots(figsize=(12, 4.5))
    ax.plot(time_axis * 1e6, voltage, linewidth=1.2)
    boundary = 0.0
    for segment in compiled.quantized_segments[:-1]:
        boundary += segment.actual_duration_s
        ax.axvline(boundary * 1e6, color="0.6", linewidth=0.7)
    ax.set_title(f"Custom sequence preview: {compiled.sequence.name}")
    ax.set_xlabel("Time within one sequence cycle (µs)")
    ax.set_ylabel("Requested connector voltage (V)")
    ax.grid(True, alpha=0.3)
    fig.tight_layout()
    _atomic_save_figure(fig, output_path)
    plt.close(fig)


def save_previews(mode, plan, output_directory):
    output_directory.mkdir(parents=True, exist_ok=True)
    if mode == "traditional":
        save_traditional_preview(plan, output_directory / "traditional_pulse.png")
    else:
        for index, compiled in enumerate(plan, start=1):
            save_custom_preview(
                compiled,
                output_directory / f"{index:02d}_{compiled.sequence.name}.png",
            )
    print(f"Preview files saved under:\n{output_directory.resolve()}")


def make_run_folder():
    timestamp = datetime.now(UK_TIME).strftime("%Y%m%d_%H%M%S")
    for suffix in range(100):
        suffix_text = "" if suffix == 0 else f"_{suffix:02d}"
        folder = OUTPUT_ROOT / f"run_{timestamp}{suffix_text}"
        try:
            folder.mkdir(parents=True, exist_ok=False)
            return folder
        except FileExistsError:
            continue
    raise RuntimeError("could not create a unique pulse-program run folder")


def save_run_configuration(mode, plan, run_folder):
    if mode == "traditional":
        plan_data = {
            "frequency_hz": plan.frequency_hz,
            "duty_cycle_percent": plan.duty_cycle_percent,
            "pulse_width_s": plan.pulse_width_s,
            "edge_time_s": plan.edge_time_s,
            "run_duration_s": TRADITIONAL_RUN_DURATION_S,
        }
    else:
        plan_data = [compiled.summary_dict() for compiled in plan]

    created_at_utc, created_at_local = _timestamp_pair()
    configuration = {
        "created_at_utc": created_at_utc,
        "created_at_local": created_at_local,
        "mode": mode,
        "moku": MOKU_IP,
        "output_channel": OUTPUT_CHANNEL,
        "low_level_v": LOW_LEVEL_V,
        "high_level_v": HIGH_LEVEL_V,
        "force_connect": FORCE_CONNECT,
        "plan": plan_data,
    }
    path = run_folder / "pulse_program.json"
    temporary_path = path.with_suffix(".json.tmp")
    temporary_path.write_text(json.dumps(configuration, indent=2), encoding="utf-8")
    temporary_path.replace(path)

    if mode == "traditional":
        save_traditional_preview(plan, run_folder / "traditional_pulse.png")
    else:
        for index, compiled in enumerate(plan, start=1):
            np.savetxt(
                run_folder / f"{index:02d}_{compiled.sequence.name}_lut.csv",
                compiled.lut_data,
                delimiter=",",
                header="normalised_lut_value",
                comments="",
            )
            save_custom_preview(
                compiled,
                run_folder / f"{index:02d}_{compiled.sequence.name}.png",
            )


def _wait_for_duration(duration_s):
    deadline = time.monotonic() + duration_s
    while True:
        remaining = deadline - time.monotonic()
        if remaining <= 0:
            return
        time.sleep(min(remaining, 0.1))


def _disable_all_awg_outputs(awg):
    """Best-effort disable of both outputs, raising after both were attempted."""
    first_error = None
    for channel in MOKU_GO_OUTPUT_CHANNELS:
        try:
            awg.enable_output(channel=channel, enable=False, strict=True)
        except Exception as error:
            if first_error is None:
                first_error = error
    if first_error is not None:
        raise first_error


def run_traditional_pulse(
    config,
    event_writer,
    *,
    instrument_factory=None,
    wait_for_duration=_wait_for_duration,
):
    """Run the traditional pulse, allowing a fake factory in automated tests."""
    if instrument_factory is None:
        try:
            from moku.instruments import Oscilloscope
        except ModuleNotFoundError as error:
            raise ModuleNotFoundError(
                "The Moku Python package is required for a real pulse run."
            ) from error
        instrument_factory = Oscilloscope

    instrument = None
    try:
        instrument = instrument_factory(MOKU_IP, force_connect=FORCE_CONNECT)
        timestamp_utc, timestamp_local = _timestamp_pair()
        event_writer.writerow(
            [timestamp_utc, timestamp_local, "connected", "traditional"]
        )
        instrument.generate_waveform(
            channel=OUTPUT_CHANNEL,
            type="Pulse",
            amplitude=config.amplitude_vpp,
            offset=config.offset_v,
            frequency=config.frequency_hz,
            pulse_width=config.pulse_width_s,
            edge_time=config.edge_time_s,
            strict=True,
        )
        timestamp_utc, timestamp_local = _timestamp_pair()
        event_writer.writerow(
            [timestamp_utc, timestamp_local, "output_enabled", "traditional"]
        )
        print("Traditional pulse output is active.")
        if TRADITIONAL_RUN_DURATION_S is None:
            print("Press Ctrl+C to stop and switch the output off.")
            while True:
                time.sleep(0.5)
        else:
            wait_for_duration(float(TRADITIONAL_RUN_DURATION_S))
    finally:
        if instrument is not None:
            try:
                instrument.generate_waveform(channel=OUTPUT_CHANNEL, type="Off")
                timestamp_utc, timestamp_local = _timestamp_pair()
                event_writer.writerow(
                    [timestamp_utc, timestamp_local, "output_disabled", ""]
                )
                print(f"Moku Output {OUTPUT_CHANNEL} is OFF.")
            finally:
                instrument.relinquish_ownership()


def run_custom_program(
    plan,
    event_writer,
    *,
    instrument_factory=None,
    wait_for_duration=_wait_for_duration,
):
    """Run custom hardware bursts, allowing fake dependencies in tests."""
    if instrument_factory is None:
        try:
            from moku.instruments import ArbitraryWaveformGenerator
        except ModuleNotFoundError as error:
            raise ModuleNotFoundError(
                "The Moku Python package is required for a real pulse run."
            ) from error
        instrument_factory = ArbitraryWaveformGenerator

    awg = None
    try:
        awg = instrument_factory(MOKU_IP, force_connect=FORCE_CONNECT)
        # manual_trigger() is device-wide.  Keep both physical outputs off so
        # stale manual-burst settings on the unused channel cannot fire.
        _disable_all_awg_outputs(awg)
        timestamp_utc, timestamp_local = _timestamp_pair()
        event_writer.writerow(
            [timestamp_utc, timestamp_local, "connected_outputs_off", "custom"]
        )

        for index, compiled in enumerate(plan, start=1):
            awg.generate_waveform(
                channel=OUTPUT_CHANNEL,
                sample_rate="Auto",
                lut_data=compiled.lut_data.tolist(),
                frequency=compiled.frequency_hz,
                amplitude=HIGH_LEVEL_V - LOW_LEVEL_V,
                offset=(HIGH_LEVEL_V + LOW_LEVEL_V) / 2.0,
                interpolation=False,
                strict=True,
            )
            # Keep the relay off until modulation is configured.  Auto chooses
            # a valid rate for the LUT; the compiler has already checked the
            # conservative Moku:Go memory/throughput table.
            awg.enable_output(channel=OUTPUT_CHANNEL, enable=False, strict=True)
            awg.disable_modulation(channel=OUTPUT_CHANNEL, strict=True)

            if compiled.sequence.repeat_count is None:
                awg.enable_output(channel=OUTPUT_CHANNEL, enable=True, strict=True)
                timestamp_utc, timestamp_local = _timestamp_pair()
                event_writer.writerow(
                    [
                        timestamp_utc,
                        timestamp_local,
                        "continuous_started",
                        compiled.sequence.name,
                    ]
                )
                print(
                    f"Continuous sequence '{compiled.sequence.name}' is active. "
                    "Press Ctrl+C to stop."
                )
                while True:
                    time.sleep(0.5)

            awg.burst_modulate(
                channel=OUTPUT_CHANNEL,
                trigger_source="Manual",
                trigger_mode="NCycle",
                burst_cycles=compiled.sequence.repeat_count,
                strict=True,
            )
            awg.enable_output(channel=OUTPUT_CHANNEL, enable=True, strict=True)
            awg.manual_trigger()
            timestamp_utc, timestamp_local = _timestamp_pair()
            event_writer.writerow(
                [
                    timestamp_utc,
                    timestamp_local,
                    "finite_burst_triggered",
                    compiled.sequence.name,
                ]
            )
            print(
                f"Triggered '{compiled.sequence.name}' "
                f"x{compiled.sequence.repeat_count}."
            )
            wait_for_duration(compiled.burst_duration_s + COMPLETION_MARGIN_S)
            awg.enable_output(channel=OUTPUT_CHANNEL, enable=False, strict=True)
            timestamp_utc, timestamp_local = _timestamp_pair()
            event_writer.writerow(
                [
                    timestamp_utc,
                    timestamp_local,
                    "finite_burst_output_disabled",
                    compiled.sequence.name,
                ]
            )
            print(f"Completed '{compiled.sequence.name}'; output is OFF.")
            if index < len(plan) and INTER_SEQUENCE_DELAY_S:
                wait_for_duration(float(INTER_SEQUENCE_DELAY_S))
    finally:
        if awg is not None:
            try:
                _disable_all_awg_outputs(awg)
                timestamp_utc, timestamp_local = _timestamp_pair()
                event_writer.writerow(
                    [
                        timestamp_utc,
                        timestamp_local,
                        "output_disabled",
                        "cleanup",
                    ]
                )
                print(f"Moku Output {OUTPUT_CHANNEL} is OFF.")
            finally:
                awg.relinquish_ownership()


def main():
    args = parse_arguments()
    mode = args.mode or PULSE_MODE
    try:
        plan = build_plan(mode)
        display_plan(mode, plan)

        if args.save_preview is not None:
            save_previews(mode, plan, args.save_preview.expanduser().resolve())

        if args.dry_run:
            print("\nDry run complete; no Moku package was imported or device opened.")
            return 0

        if REQUIRE_START_CONFIRMATION and not args.yes:
            confirmation = input(
                "\nVerify the requested connector voltage and EOM setup, "
                "then type START: "
            ).strip()
            if confirmation != "START":
                print("Start cancelled; no Moku connection was opened.")
                return 0

        run_folder = make_run_folder()
        save_run_configuration(mode, plan, run_folder)
        event_path = run_folder / "pulse_events.csv"
        interrupted = False
        with event_path.open("w", newline="", encoding="utf-8", buffering=1) as file:
            writer = csv.writer(file)
            writer.writerow(
                ["timestamp_utc", "timestamp_local", "event", "sequence_name"]
            )
            try:
                if mode == "traditional":
                    run_traditional_pulse(plan, writer)
                else:
                    run_custom_program(plan, writer)
            except KeyboardInterrupt:
                interrupted = True
                print("\nPulse output stop requested by operator.")

        print(f"Pulse-program record saved to:\n{run_folder}")
        return 130 if interrupted else 0
    except (FileNotFoundError, ModuleNotFoundError, RuntimeError, ValueError) as error:
        print(f"\nERROR: {error}", file=sys.stderr)
        return 2


if __name__ == "__main__":
    raise SystemExit(main())
